services:
  - type: web
    name: medical-chatbot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_HOST
        sync: false
      - key: PINECONE_INDEX_NAME
        value: medicalbot
      - key: FRONTEND_URL
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.11
